# Generated by Django 5.0.1 on 2025-10-28 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField(blank=True, default=dict, help_text='Dados adicionais coletados no formulário de inscrição', verbose_name='Dados do Formulário')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Aguardando Pagamento'), ('PAID', 'Pago'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado')], default='PENDING_PAYMENT', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(blank=True, choices=[('PIX_CASH', 'PIX à Vista'), ('PIX_INSTALLMENT', 'PIX Parcelado'), ('CREDIT_CARD', 'Cartão de Crédito')], max_length=20, null=True, verbose_name='Método de Pagamento')),
                ('installments', models.IntegerField(default=1, help_text='1 para pagamento à vista', verbose_name='Número de Parcelas')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Valor original do lote', max_digits=10, verbose_name='Valor Total')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Desconto')),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='Valor após desconto', max_digits=10, verbose_name='Valor Final')),
                ('admin_notes', models.TextField(blank=True, help_text='Notas internas visíveis apenas para administradores', verbose_name='Observações do Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='products.batch', verbose_name='Lote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='products.product', verbose_name='Produto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='enrollments_user_id_963010_idx'), models.Index(fields=['batch', 'status'], name='enrollments_batch_i_ca22c6_idx')],
            },
        ),
    ]
