# Generated by Django 5.0.1 on 2025-11-02 01:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        ('products', '0002_product_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor do desconto aplicado pelo cupom', max_digits=10, verbose_name='Desconto do Cupom'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto total (PIX + Cupom)', max_digits=10, verbose_name='Valor do Desconto'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único do cupom (ex: PROMO2024)', max_length=50, unique=True, verbose_name='Código do Cupom')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Porcentagem'), ('FIXED', 'Valor Fixo')], default='PERCENTAGE', max_length=20, verbose_name='Tipo de Desconto')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Porcentagem (0-100) ou valor fixo em R$', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor do Desconto')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Limite máximo de desconto (apenas para porcentagem)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desconto Máximo')),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo para usar o cupom', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Compra Mínima')),
                ('max_uses', models.IntegerField(blank=True, help_text='Número máximo de vezes que o cupom pode ser usado (deixe vazio para ilimitado)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Usos Máximos')),
                ('uses_count', models.IntegerField(default=0, verbose_name='Contador de Usos')),
                ('valid_from', models.DateTimeField(help_text='Data/hora de início da validade', verbose_name='Válido De')),
                ('valid_until', models.DateTimeField(help_text='Data/hora de fim da validade', verbose_name='Válido Até')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('description', models.TextField(blank=True, help_text='Descrição interna do cupom', verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, help_text='Deixe vazio para aplicar a todos os produtos', to='products.product', verbose_name='Produtos')),
            ],
            options={
                'verbose_name': 'Cupom de Desconto',
                'verbose_name_plural': 'Cupons de Desconto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='enrollments.coupon', verbose_name='Cupom de Desconto'),
        ),
    ]
