# Generated by Django 5.2.8 on 2026-02-01 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_coupon_enable_12x_installments'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_installments',
            field=models.IntegerField(default=6, help_text='Número máximo de parcelas permitidas com este cupom (padrão: 6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Máximo de Parcelas'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='enable_12x_installments',
            field=models.BooleanField(default=False, help_text='Se marcado, usa o valor de "Máximo de Parcelas" abaixo', verbose_name='Habilitar Parcelamento Especial'),
        ),
    ]
