# Generated by Django 5.2.8 on 2026-02-01 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_add_coupon_max_installments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_installments', models.IntegerField(default=6, help_text='Número máximo de parcelas permitidas por padrão (sem cupom especial)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Máximo de Parcelas Padrão')),
                ('max_installments_with_coupon', models.IntegerField(default=10, help_text='Número máximo de parcelas permitidas quando cupom especial é aplicado', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Máximo de Parcelas com Cupom')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configurações',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
