# Generated by Django 5.0.1 on 2025-10-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Pagamento Asaas')),
                ('asaas_subscription_id', models.CharField(blank=True, help_text='Para pagamentos recorrentes/parcelados', max_length=100, null=True, verbose_name='ID Assinatura Asaas')),
                ('installment_number', models.IntegerField(default=1, help_text='Qual parcela este pagamento representa (1-8)', verbose_name='Número da Parcela')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('CREATED', 'Criado'), ('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('RECEIVED', 'Recebido'), ('OVERDUE', 'Vencido'), ('REFUNDED', 'Reembolsado'), ('CANCELLED', 'Cancelado')], default='CREATED', max_length=20, verbose_name='Status')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('payment_url', models.URLField(blank=True, help_text='URL do boleto ou checkout', max_length=500, verbose_name='URL de Pagamento')),
                ('pix_qr_code', models.TextField(blank=True, help_text='Código QR do PIX em base64', verbose_name='QR Code PIX')),
                ('pix_copy_paste', models.TextField(blank=True, help_text='Código PIX para copiar e colar', verbose_name='PIX Copia e Cola')),
                ('raw_webhook_data', models.JSONField(blank=True, default=dict, help_text='Dados brutos recebidos do webhook Asaas', verbose_name='Dados do Webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='enrollments.enrollment', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enrollment', 'status'], name='payments_pa_enrollm_ab85b8_idx'), models.Index(fields=['asaas_payment_id'], name='payments_pa_asaas_p_84cc80_idx')],
            },
        ),
    ]
