# Generated by Django 5.0.1 on 2025-10-28 15:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço Base')),
                ('max_installments', models.IntegerField(default=8, help_text='Número máximo de parcelas permitidas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Máximo de Parcelas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Lote 1 - Early Bird, Lote 2 - Regular', max_length=100, verbose_name='Nome do Lote')),
                ('start_date', models.DateTimeField(verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(verbose_name='Data de Término')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço específico deste lote (sobrescreve preço base)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço do Lote')),
                ('pix_discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Desconto percentual para pagamento PIX à vista', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto PIX (%)')),
                ('max_enrollments', models.IntegerField(blank=True, help_text='Deixe em branco para ilimitado', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Limite de Vagas')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendado'), ('ACTIVE', 'Ativo'), ('FULL', 'Esgotado'), ('ENDED', 'Encerrado')], default='SCHEDULED', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['start_date'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
