# Generated by Django 5.0.1 on 2025-10-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='event_date',
            field=models.DateTimeField(blank=True, help_text='Data de início do evento/acampamento', null=True, verbose_name='Data do Evento'),
        ),
    ]
