# Generated by Django 5.2.8 on 2025-11-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_separate_prices'),
        ('products', '0002_product_event_date'),
    ]

    operations = [
    ]
